sudo: required
services: 
  - docker

before_install:
  - docker build -t gianlu21/docker-react/smartcity/ -f Dockerfile .

script:
  - docker run -e CI=true gianlu21/docker-react/smartcity/ npm run test