version: '3.4'
services: 
  web:
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes: 
      - /app/src/node_modules
      - .:/app/src